robot_ip: "192.168.57.2"
# camera_ids:
#   front: "000000000000"
#   hand: "000000000000"
# gelsight_ids:
#   tactile_left: "GelSight Mini R0B 2BNK-CE0U: Ge"
#   tactile_right: "GelSight Mini R0B 2BG8-0H3X: Ge"
gripper_hand_type: "right"
gripper_modbus_port: "/dev/ttyUSB0"
# Dry-run mode: tests command transmission without connecting to actual hardware
dry_run: true
